### PR TITLE
import global from terria

### PR DESCRIPTION
**Pull request by chloeleichen**
This is to replace https://github.com/TerriaJS/aremi-natmap/pull/54

### CODE REVIEW

**Comment by RacingTadpole** [comment]
Seems to be a build error?
`ERROR in ./index.js
Module not found: Error: Cannot resolve module 'terriajs/lib/ViewModels/GNAFSearchProviderViewModel.js' in /home/travis/build/TerriaJS/aremi-natmap
 @ ./index.js 65:35-100`

**Comment by rdengate** [comment]
Looks like AREMI hasn't merged from TerriaMap/NationalMap lately or it would have the fix for that. I've added it to master.

**Comment by RacingTadpole** [comment]
thanks! could you also merge it into this PR?

**Comment by rdengate** [comment]
@RacingTadpole done :-)

**Comment by RacingTadpole** [comment]
@rdengate does your change to master above work with the stated version of terriajs in package.json (4.2.0)? Just checking :-)  @chloeleichen, does this PR work with that version?
If we're not sure, let's just hold off merging this until we have a newly published version of terriajs.

**Comment by rdengate** [comment]
@RacingTadpole yep, I confirm that my change works with TerriaJS 4.2.0 and later.

**Pull request merged**
